brightness_range = [0.35, 1]
temperature_range = [2300, 6500]

[wallpapers]
root = "/home/v/Wallpapers"
morning = "1929.jpg"
day = "AndreySakharov.jpg"
evening = "girl_with_a_perl_earring.jpg"
night = "starry_night.jpg"
